version: '3.8'

services:
  db:
    image: postgres:16.2
    container_name: postgres_db_universe
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5117:5432"
    volumes:
      - db_data:/var/lib/postgresql/data_r
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  adminer:
    image: adminer:latest
    container_name: adminer_universe_c
    ports:
      - "7075:8080"  # Adminer uses port 8080 in the container
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge